version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9.4-management
    container_name: imagetools_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbitmq_net

  admin:
    build:
      context: admin
    container_name: imagetools_admin
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

  fastapi:
    build:
      context: ./fastapi
    container_name: imagetools_fastapi
    ports:
      - 8000:8000
    volumes:
      - ./uploaded:/app/uploaded
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge