services:
  rabbitmq:
    image: rabbitmq:3.9.4-management
    container_name: imagetools_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbitmq_net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  admin:
    build:
      context: admin
    container_name: imagetools_admin
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

  app:
    build:
      context: app
    container_name: imagetools_app
    ports:
      - 8000:8000
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

  celery_worker:
    build:
      context: ./app
    container_name: imagetools_celery_worker
    command: celery -A celery_tasks.celery worker --loglevel=debug
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_net

  flower:
    image: mher/flower
    container_name: imagetools_flower
    command: celery flower --persisten=True
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge