services:
  rabbitmq:
    image: rabbitmq:3.9.4-management
    container_name: imagetools_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - rabbitmq_net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  admin:
    build:
      context: admin
    container_name: imagetools_admin
    depends_on:
      - rabbitmq
    ports:
      - 5000:5000
    volumes:
      - ./uploaded:/app/uploaded
      - ./uploaded:/app/static/uploaded
      - ./results:/app/static/results
      - ./success:/app/static/success
    networks:
      - rabbitmq_net

  app:
    build:
      context: app
    container_name: imagetools_app
    ports:
      - 8000:8000
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
      - ./samples:/app/samples
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

  compress_worker_1:
    build:
      context: ./app
    container_name: imagetools_compress_worker_1
    command: celery -A celery_tasks.celery worker -Q imagetools.compress_image_queue --loglevel=debug --hostname=compress_worker_1@%h
#    command: celery -A celery_tasks.celery worker --loglevel=debug --hostname=imagetools_worker_1@%h
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_net

  compress_worker_2:
    build:
      context: ./app
    container_name: imagetools_compress_worker_2
    command: celery -A celery_tasks.celery worker -Q imagetools.compress_image_queue --loglevel=debug --hostname=compress_worker_2@%h
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_net

  upscale_worker_1:
    build:
      context: ./app
    container_name: imagetools_upscale_worker_1
    command: celery -A celery_tasks.celery worker -Q imagetools.upscale_image_queue --loglevel=debug --hostname=upscale_worker_1@%h
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_net

  upscale_worker_2:
    build:
      context: ./app
    container_name: imagetools_upscale_worker_2
    command: celery -A celery_tasks.celery worker -Q imagetools.upscale_image_queue --loglevel=debug --hostname=upscale_worker_2@%h
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_net

  upscale_worker_3:
    build:
      context: ./app
    container_name: imagetools_upscale_worker_3
    command: celery -A celery_tasks.celery worker -Q imagetools.upscale_image_queue --loglevel=debug --hostname=upscale_worker_3@%h
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_net

  extract_worker_1:
    build:
      context: ./app
    container_name: imagetools_extract_worker_1
    command: celery -A celery_tasks.celery worker -Q imagetools.extract_text_queue --loglevel=debug --hostname=extract_worker_1@%h
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_net

  extract_worker_2:
    build:
      context: ./app
    container_name: imagetools_extract_worker_2
    command: celery -A celery_tasks.celery worker -Q imagetools.extract_text_queue --loglevel=debug --hostname=extract_worker_2@%h
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_net

  extract_worker_3:
    build:
      context: ./app
    container_name: imagetools_extract_worker_3
    command: celery -A celery_tasks.celery worker -Q imagetools.extract_text_queue --loglevel=debug --hostname=extract_worker_3@%h
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_net

  extract_worker_4:
    build:
      context: ./app
    container_name: imagetools_extract_worker_4
    command: celery -A celery_tasks.celery worker -Q imagetools.extract_text_queue --loglevel=debug --hostname=extract_worker_4@%h
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_net

  extract_worker_5:
    build:
      context: ./app
    container_name: imagetools_extract_worker_5
    command: celery -A celery_tasks.celery worker -Q imagetools.extract_text_queue --loglevel=debug --hostname=extract_worker_5@%h
    volumes:
      - ./uploaded:/app/uploaded
      - ./results:/app/results
      - ./success:/app/success
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_net

  flower:
    image: mher/flower
    container_name: imagetools_flower
    command: celery flower --persisten=True
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq//
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge